function plotWeightedCentroidApp(track)
    all1 = track.WeightedCentroid(:,1:2:end);
    all2 = track.WeightedCentroid(:,2:2:end);

    plot(all1(1),all2(1),'-o',...
        'LineWidth',1,...
        'MarkerSize',5,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','b')
    plot(all1(end),all2(end),'-o',...
        'LineWidth',1,...
        'MarkerSize',5,...
        'MarkerEdgeColor','k',...
        'MarkerFaceColor','r')
    plot(all1(:),all2(:),'k','LineWidth',0.5);
end